version: '3'
services:
  client:
    # will build ./client/Dockerfile
    build: ./client
    ports:
    - "80:80"
  server:
    # will build ./server/Dockerfile
    build: ./server
    ports:
      - "5000:5000"

    privileged:
      true